package views.rendimiento.buque;

import controllers.RendimientoBuqueController;
import controllers.Util;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Fenyr Shell
 */
public class Create extends javax.swing.JFrame {

    /**
     * Creates new form RendimientoBuque
     */
    public Create() {
        initComponents();
        Calendar calendar = Calendar.getInstance();
        datePuertoArribo.setCalendar(calendar);
        datePuertoDesatraque.setCalendar(calendar);
        dateMuelleAtraque.setCalendar(calendar);
        dateOperacionInicio.setCalendar(calendar);
        dateOperacionTermino.setCalendar(calendar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnBuquePuerto = new javax.swing.JPanel();
        txtPuertoMuelle = new javax.swing.JTextField();
        lblPuertoProducto = new javax.swing.JLabel();
        txtPuertoProducto = new javax.swing.JTextField();
        txtPuertoBuque = new javax.swing.JTextField();
        txtPuertoTonelaje = new javax.swing.JTextField();
        lblPuertoBuque = new javax.swing.JLabel();
        lblPuertoMuelle = new javax.swing.JLabel();
        lblPuertoTonelaje = new javax.swing.JLabel();
        datePuertoArribo = new com.toedter.calendar.JDateChooser();
        lblPuertoArribo = new javax.swing.JLabel();
        lblPuertoArriboHora = new javax.swing.JLabel();
        txtPuertoArriboHora = new javax.swing.JTextField();
        txtPuertoDesatraqueHora = new javax.swing.JTextField();
        lblPuertoDesatraqueHora = new javax.swing.JLabel();
        datePuertoDesatraque = new com.toedter.calendar.JDateChooser();
        lblPuertoDesatraque = new javax.swing.JLabel();
        pnBuqueMuelle = new javax.swing.JPanel();
        txtMuelleAtraqueHora = new javax.swing.JTextField();
        lblMuelleAtraqueHora = new javax.swing.JLabel();
        dateMuelleAtraque = new com.toedter.calendar.JDateChooser();
        lblMuelleAtraque = new javax.swing.JLabel();
        pnBuqueOperacion = new javax.swing.JPanel();
        txtOperacionDemoras = new javax.swing.JTextField();
        lblOperacionDemoras = new javax.swing.JLabel();
        dateOperacionInicio = new com.toedter.calendar.JDateChooser();
        lblOperacionInicio = new javax.swing.JLabel();
        lblOperacionInicioHora = new javax.swing.JLabel();
        txtOperacionInicioHora = new javax.swing.JTextField();
        txtOperacionTerminoHora = new javax.swing.JTextField();
        lblOperacionTerminoHora = new javax.swing.JLabel();
        dateOperacionTermino = new com.toedter.calendar.JDateChooser();
        lblOperacionTermino = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnPreview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rendimiento de Buques");

        root.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rendimiento de Buques");

        pnBuquePuerto.setBorder(javax.swing.BorderFactory.createTitledBorder("BUQUE EN PUERTO"));

        txtPuertoMuelle.setText("7");

        lblPuertoProducto.setText("Producto:");

        txtPuertoProducto.setText("Maiz Amarillo");

        txtPuertoBuque.setText("Atlantic Tulum");
        txtPuertoBuque.setName("Buque"); // NOI18N

        txtPuertoTonelaje.setText("34097");
        txtPuertoTonelaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuertoTonelajeKeyTyped(evt);
            }
        });

        lblPuertoBuque.setText("Buque:");

        lblPuertoMuelle.setText("Muelle:");

        lblPuertoTonelaje.setText("Tonelaje:");

        lblPuertoArribo.setText("Arribo:");

        lblPuertoArriboHora.setText("Hora:");

        txtPuertoArriboHora.setText("6");
        txtPuertoArriboHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuertoArriboHoraKeyTyped(evt);
            }
        });

        txtPuertoDesatraqueHora.setText("8.5");
        txtPuertoDesatraqueHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPuertoDesatraqueHoraKeyTyped(evt);
            }
        });

        lblPuertoDesatraqueHora.setText("Hora:");

        lblPuertoDesatraque.setText("Desatraque:");

        javax.swing.GroupLayout pnBuquePuertoLayout = new javax.swing.GroupLayout(pnBuquePuerto);
        pnBuquePuerto.setLayout(pnBuquePuertoLayout);
        pnBuquePuertoLayout.setHorizontalGroup(
            pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuquePuertoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPuertoProducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuertoBuque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuertoArribo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuertoDesatraque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuquePuertoLayout.createSequentialGroup()
                        .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(datePuertoDesatraque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datePuertoArribo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnBuquePuertoLayout.createSequentialGroup()
                                .addComponent(lblPuertoArriboHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuertoArriboHora))
                            .addGroup(pnBuquePuertoLayout.createSequentialGroup()
                                .addComponent(lblPuertoDesatraqueHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPuertoDesatraqueHora))))
                    .addGroup(pnBuquePuertoLayout.createSequentialGroup()
                        .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPuertoProducto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPuertoBuque, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPuertoMuelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPuertoTonelaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPuertoTonelaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtPuertoMuelle, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnBuquePuertoLayout.setVerticalGroup(
            pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuquePuertoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuertoBuque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPuertoBuque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuertoMuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPuertoMuelle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuertoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPuertoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPuertoTonelaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPuertoTonelaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuertoArribo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePuertoArribo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuertoArriboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPuertoArriboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuertoDesatraque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePuertoDesatraque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuquePuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPuertoDesatraqueHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPuertoDesatraqueHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnBuqueMuelle.setBorder(javax.swing.BorderFactory.createTitledBorder("BUQUE EN MUELLE"));

        txtMuelleAtraqueHora.setText("18.1");
        txtMuelleAtraqueHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMuelleAtraqueHoraKeyTyped(evt);
            }
        });

        lblMuelleAtraqueHora.setText("Hora:");

        lblMuelleAtraque.setText("Atraque:");

        javax.swing.GroupLayout pnBuqueMuelleLayout = new javax.swing.GroupLayout(pnBuqueMuelle);
        pnBuqueMuelle.setLayout(pnBuqueMuelleLayout);
        pnBuqueMuelleLayout.setHorizontalGroup(
            pnBuqueMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuqueMuelleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMuelleAtraque, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateMuelleAtraque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMuelleAtraqueHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMuelleAtraqueHora)
                .addContainerGap())
        );
        pnBuqueMuelleLayout.setVerticalGroup(
            pnBuqueMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuqueMuelleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuqueMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMuelleAtraque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateMuelleAtraque, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuqueMuelleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMuelleAtraqueHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMuelleAtraqueHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnBuqueOperacion.setBorder(javax.swing.BorderFactory.createTitledBorder("BUQUE EN OPERACIÓN"));

        txtOperacionDemoras.setText("0");
        txtOperacionDemoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOperacionDemorasKeyTyped(evt);
            }
        });

        lblOperacionDemoras.setText("Demoras");

        lblOperacionInicio.setText("Inicio Op.");

        lblOperacionInicioHora.setText("Hora:");

        txtOperacionInicioHora.setText("6");
        txtOperacionInicioHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOperacionInicioHoraKeyTyped(evt);
            }
        });

        txtOperacionTerminoHora.setText("6");
        txtOperacionTerminoHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOperacionTerminoHoraKeyTyped(evt);
            }
        });

        lblOperacionTerminoHora.setText("Hora:");

        lblOperacionTermino.setText("Termino Op.");

        javax.swing.GroupLayout pnBuqueOperacionLayout = new javax.swing.GroupLayout(pnBuqueOperacion);
        pnBuqueOperacion.setLayout(pnBuqueOperacionLayout);
        pnBuqueOperacionLayout.setHorizontalGroup(
            pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuqueOperacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblOperacionDemoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOperacionTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOperacionInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOperacionDemoras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnBuqueOperacionLayout.createSequentialGroup()
                        .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateOperacionTermino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateOperacionInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnBuqueOperacionLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblOperacionInicioHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOperacionInicioHora))
                            .addGroup(pnBuqueOperacionLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblOperacionTerminoHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOperacionTerminoHora)))))
                .addContainerGap())
        );
        pnBuqueOperacionLayout.setVerticalGroup(
            pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBuqueOperacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperacionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOperacionInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOperacionInicioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtOperacionInicioHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOperacionTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateOperacionTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblOperacionTerminoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtOperacionTerminoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnBuqueOperacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOperacionDemoras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOperacionDemoras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnPreview.setText("Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnBuquePuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBuqueMuelle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnBuqueOperacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPreview)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pnBuquePuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnBuqueMuelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnBuqueOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        root.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(root)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (Util.fieldIsEmpty(txtPuertoBuque, txtPuertoMuelle, txtPuertoProducto, 
                txtPuertoTonelaje, txtPuertoArriboHora, txtPuertoDesatraqueHora,
                txtMuelleAtraqueHora, txtOperacionInicioHora, txtOperacionTerminoHora, 
                txtOperacionDemoras) || Util.dateIsEmpty(datePuertoArribo, datePuertoDesatraque,
                dateMuelleAtraque, dateOperacionInicio, dateOperacionTermino)) {
            
            JOptionPane.showMessageDialog(rootPane, "Llena todos los campos!");
        }else {
            String puertoBuque = txtPuertoBuque.getText();
            String puertoMuelle = txtPuertoMuelle.getText();
            String puertoProducto = txtPuertoProducto.getText();
            double puertoTonelaje = Double.parseDouble(txtPuertoTonelaje.getText());
            Date puertoArribo = datePuertoArribo.getDate();
            double puertoArriboHora = Double.parseDouble(txtPuertoArriboHora.getText());
            Date puertoDesatraque = datePuertoDesatraque.getDate();
            double puertoDesatraqueHora = Double.parseDouble(txtPuertoDesatraqueHora.getText());
            Date muelleAtraque = dateMuelleAtraque.getDate();
            double muelleAtraqueHora = Double.parseDouble(txtMuelleAtraqueHora.getText());
            Date operacionInicio = dateOperacionInicio.getDate();
            double operacionInicioHora = Double.parseDouble(txtOperacionInicioHora.getText());
            Date operacionTermino = dateOperacionTermino.getDate();
            double operacionTerminoHora = Double.parseDouble(txtOperacionTerminoHora.getText());
            double operacionDemoras = Double.parseDouble(txtOperacionDemoras.getText());

            JOptionPane.showMessageDialog(rootPane, "Función no disponible!", "Preview", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPuertoTonelajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuertoTonelajeKeyTyped
        // TODO add your handling code here:
        Util.onlyNumber(this, evt);
    }//GEN-LAST:event_txtPuertoTonelajeKeyTyped

    private void txtPuertoArriboHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuertoArriboHoraKeyTyped
        // TODO add your handling code here:
        Util.onlyNumber(this, evt);
    }//GEN-LAST:event_txtPuertoArriboHoraKeyTyped

    private void txtPuertoDesatraqueHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPuertoDesatraqueHoraKeyTyped
        // TODO add your handling code here:
        Util.onlyNumber(this, evt);
    }//GEN-LAST:event_txtPuertoDesatraqueHoraKeyTyped

    private void txtMuelleAtraqueHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMuelleAtraqueHoraKeyTyped
        // TODO add your handling code here:
        Util.onlyNumber(this, evt);
    }//GEN-LAST:event_txtMuelleAtraqueHoraKeyTyped

    private void txtOperacionInicioHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOperacionInicioHoraKeyTyped
        // TODO add your handling code here:
        Util.onlyNumber(this, evt);
    }//GEN-LAST:event_txtOperacionInicioHoraKeyTyped

    private void txtOperacionTerminoHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOperacionTerminoHoraKeyTyped
        // TODO add your handling code here:
        Util.onlyNumber(this, evt);
    }//GEN-LAST:event_txtOperacionTerminoHoraKeyTyped

    private void txtOperacionDemorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOperacionDemorasKeyTyped
        // TODO add your handling code here:
        Util.onlyNumber(this, evt);
    }//GEN-LAST:event_txtOperacionDemorasKeyTyped

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
        if (Util.fieldIsEmpty(txtPuertoBuque, txtPuertoMuelle, txtPuertoProducto, 
                txtPuertoTonelaje, txtPuertoArriboHora, txtPuertoDesatraqueHora,
                txtMuelleAtraqueHora, txtOperacionInicioHora, txtOperacionTerminoHora, 
                txtOperacionDemoras) || Util.dateIsEmpty(datePuertoArribo, datePuertoDesatraque,
                dateMuelleAtraque, dateOperacionInicio, dateOperacionTermino)) {
            
            JOptionPane.showMessageDialog(rootPane, "Llena todos los campos!");
        }else {
            String puertoBuque = txtPuertoBuque.getText();
            String puertoMuelle = txtPuertoMuelle.getText();
            String puertoProducto = txtPuertoProducto.getText();
            double puertoTonelaje = Double.parseDouble(txtPuertoTonelaje.getText());
            Date puertoArribo = datePuertoArribo.getDate();
            double puertoArriboHora = Double.parseDouble(txtPuertoArriboHora.getText());
            Date puertoDesatraque = datePuertoDesatraque.getDate();
            double puertoDesatraqueHora = Double.parseDouble(txtPuertoDesatraqueHora.getText());
            double puertoZarpe = 1;
            Date muelleAtraque = dateMuelleAtraque.getDate();
            double muelleAtraqueHora = Double.parseDouble(txtMuelleAtraqueHora.getText());
            Date operacionInicio = dateOperacionInicio.getDate();
            double operacionInicioHora = Double.parseDouble(txtOperacionInicioHora.getText());
            Date operacionTermino = dateOperacionTermino.getDate();
            double operacionTerminoHora = Double.parseDouble(txtOperacionTerminoHora.getText());
            double operacionDemoras = Double.parseDouble(txtOperacionDemoras.getText());
                        
            RendimientoBuqueController rbc = new RendimientoBuqueController();
            rbc.show(puertoBuque, puertoMuelle, puertoProducto, puertoTonelaje, 
                    puertoArribo, puertoArriboHora, puertoDesatraque, puertoDesatraqueHora, puertoZarpe,
                    muelleAtraque, muelleAtraqueHora, operacionInicio, operacionInicioHora,
                    operacionTermino, operacionTerminoHora, operacionDemoras);
        }
    }//GEN-LAST:event_btnPreviewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPreview;
    private com.toedter.calendar.JDateChooser dateMuelleAtraque;
    private com.toedter.calendar.JDateChooser dateOperacionInicio;
    private com.toedter.calendar.JDateChooser dateOperacionTermino;
    private com.toedter.calendar.JDateChooser datePuertoArribo;
    private com.toedter.calendar.JDateChooser datePuertoDesatraque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblMuelleAtraque;
    private javax.swing.JLabel lblMuelleAtraqueHora;
    private javax.swing.JLabel lblOperacionDemoras;
    private javax.swing.JLabel lblOperacionInicio;
    private javax.swing.JLabel lblOperacionInicioHora;
    private javax.swing.JLabel lblOperacionTermino;
    private javax.swing.JLabel lblOperacionTerminoHora;
    private javax.swing.JLabel lblPuertoArribo;
    private javax.swing.JLabel lblPuertoArriboHora;
    private javax.swing.JLabel lblPuertoBuque;
    private javax.swing.JLabel lblPuertoDesatraque;
    private javax.swing.JLabel lblPuertoDesatraqueHora;
    private javax.swing.JLabel lblPuertoMuelle;
    private javax.swing.JLabel lblPuertoProducto;
    private javax.swing.JLabel lblPuertoTonelaje;
    private javax.swing.JPanel pnBuqueMuelle;
    private javax.swing.JPanel pnBuqueOperacion;
    private javax.swing.JPanel pnBuquePuerto;
    private javax.swing.JScrollPane root;
    private javax.swing.JTextField txtMuelleAtraqueHora;
    private javax.swing.JTextField txtOperacionDemoras;
    private javax.swing.JTextField txtOperacionInicioHora;
    private javax.swing.JTextField txtOperacionTerminoHora;
    private javax.swing.JTextField txtPuertoArriboHora;
    private javax.swing.JTextField txtPuertoBuque;
    private javax.swing.JTextField txtPuertoDesatraqueHora;
    private javax.swing.JTextField txtPuertoMuelle;
    private javax.swing.JTextField txtPuertoProducto;
    private javax.swing.JTextField txtPuertoTonelaje;
    // End of variables declaration//GEN-END:variables
}
